# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 01:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_feedback_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.AddField(
            model_name='surveysheet',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.UserInfo', verbose_name='创建人'),
        ),
    ]
