# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20171101_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyoption',
            name='option',
            field=models.IntegerField(choices=[(1, '打分'), (2, '判断'), (3, '问答')], default=1, verbose_name='问题类型'),
        ),
        migrations.AlterField(
            model_name='surveyoption',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.SurveySheet', verbose_name='所属主表'),
        ),
    ]
