# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20171101_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.SurveySheet'),
        ),
        migrations.AlterField(
            model_name='surveyoption',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.SurveySheet', verbose_name='所属主表'),
        ),
    ]
