# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20171102_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='score',
            field=models.IntegerField(null=True, verbose_name='打分'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.SurveyOption'),
        ),
        migrations.AlterField(
            model_name='surveyoption',
            name='option',
            field=models.IntegerField(choices=[(1, '打分'), (2, '问答')], default=1, verbose_name='问题类型'),
        ),
    ]
